group=dev.quire
version=26.3-R0.1-SNAPSHOT
mcVersion=26.3
apiVersion=26.3
channel=EXPERIMENTAL
# Pinned PaperMC/Paper commit (26.3 build 135)
paperRef=abfdaed87a695450cdaa5711ec52833b3ce8997d

updatingMinecraft=false

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
